openapi: 3.0.3
info:
  title: Injective Guilds Service
  description: HTTP server for the Trading guilds query
  version: "1.0"
servers:
- url: http://0.0.0.0:9930
paths:
  /guilds:
    get:
      tags:
      - GuildsService
      summary: GetAllGuilds GuildsService
      description: Get all guilds
      operationId: GuildsService#GetAllGuilds
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllGuildsResponseBody'
              example:
                guilds:
                - capacity: 2512663142570487689
                  derivative_quote_requirement: Ut suscipit iste ex.
                  description: Id et quaerat cum.
                  id: Aut est sint illum.
                  master_address: Ut sunt aut consectetur.
                  member_count: 45528291560320936
                  name: Voluptatem maiores nulla incidunt quasi quibusdam et.
                  spot_base_requirement: Est fuga vel quos rerum.
                  spot_quote_requirement: Sit ut.
                  staking_requirement: Hic accusantium est nobis dolores.
                - capacity: 2512663142570487689
                  derivative_quote_requirement: Ut suscipit iste ex.
                  description: Id et quaerat cum.
                  id: Aut est sint illum.
                  master_address: Ut sunt aut consectetur.
                  member_count: 45528291560320936
                  name: Voluptatem maiores nulla incidunt quasi quibusdam et.
                  spot_base_requirement: Est fuga vel quos rerum.
                  spot_quote_requirement: Sit ut.
                  staking_requirement: Hic accusantium est nobis dolores.
                - capacity: 2512663142570487689
                  derivative_quote_requirement: Ut suscipit iste ex.
                  description: Id et quaerat cum.
                  id: Aut est sint illum.
                  master_address: Ut sunt aut consectetur.
                  member_count: 45528291560320936
                  name: Voluptatem maiores nulla incidunt quasi quibusdam et.
                  spot_base_requirement: Est fuga vel quos rerum.
                  spot_quote_requirement: Sit ut.
                  staking_requirement: Hic accusantium est nobis dolores.
                - capacity: 2512663142570487689
                  derivative_quote_requirement: Ut suscipit iste ex.
                  description: Id et quaerat cum.
                  id: Aut est sint illum.
                  master_address: Ut sunt aut consectetur.
                  member_count: 45528291560320936
                  name: Voluptatem maiores nulla incidunt quasi quibusdam et.
                  spot_base_requirement: Est fuga vel quos rerum.
                  spot_quote_requirement: Sit ut.
                  staking_requirement: Hic accusantium est nobis dolores.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}:
    get:
      tags:
      - GuildsService
      summary: GetSingleGuild GuildsService
      description: Get a single guild base on ID
      operationId: GuildsService#GetSingleGuild
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Expedita quaerat quia hic.
        example: Rerum at consequuntur sint animi.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSingleGuildResponseBody'
              example:
                guild:
                  capacity: 2512663142570487689
                  derivative_quote_requirement: Ut suscipit iste ex.
                  description: Id et quaerat cum.
                  id: Aut est sint illum.
                  master_address: Ut sunt aut consectetur.
                  member_count: 45528291560320936
                  name: Voluptatem maiores nulla incidunt quasi quibusdam et.
                  spot_base_requirement: Est fuga vel quos rerum.
                  spot_quote_requirement: Sit ut.
                  staking_requirement: Hic accusantium est nobis dolores.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/default-member:
    get:
      tags:
      - GuildsService
      summary: GetGuildDefaultMember GuildsService
      description: Get default guild member
      operationId: GuildsService#GetGuildDefaultMember
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Nostrum rem.
        example: Laboriosam culpa.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGuildDefaultMemberResponseBody'
              example:
                default_member:
                  injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
                  is_default_guild_member: false
                  since: 4230233166174377582
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/guild-master:
    get:
      tags:
      - GuildsService
      summary: GetGuildMasterAddress GuildsService
      description: Get master address of given guild
      operationId: GuildsService#GetGuildMasterAddress
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Sit et voluptatem repudiandae.
        example: Deserunt quia possimus aspernatur beatae.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGuildMasterAddressResponseBody'
              example:
                master_address: Recusandae minima ipsam.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/markets:
    get:
      tags:
      - GuildsService
      summary: GetGuildMarkets GuildsService
      description: Get the guild markets
      operationId: GuildsService#GetGuildMarkets
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Vel repellat fugiat.
        example: Nemo provident unde.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGuildMarketsResponseBody'
              example:
                markets:
                - is_perpetual: false
                  market_id: Voluptatem ut labore.
                - is_perpetual: false
                  market_id: Voluptatem ut labore.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/member:
    delete:
      tags:
      - GuildsService
      summary: LeaveGuild GuildsService
      description: 'Enter the guild: Should supply public_key, message, signature
        in base64'
      operationId: GuildsService#LeaveGuild
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Inventore est quaerat tenetur.
        example: Cumque eius.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnterGuildRequestBody'
            example:
              message: At quasi necessitatibus maxime enim.
              public_key: Et placeat id.
              signature: Id alias at magnam ut.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaveGuildResponseBody'
              example:
                leave_status: Quia natus iste eaque.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - GuildsService
      summary: EnterGuild GuildsService
      description: 'Enter the guild: Should supply public_key, message, signature
        in base64'
      operationId: GuildsService#EnterGuild
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Accusantium et in velit atque beatae.
        example: Harum quo tenetur numquam fugiat asperiores aut.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnterGuildRequestBody'
            example:
              message: Nihil quia quo eligendi omnis.
              public_key: Dolore atque aperiam officiis necessitatibus dicta est.
              signature: Adipisci sed libero a nam consectetur.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnterGuildResponseBody'
              example:
                join_status: Voluptates est.
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/members:
    get:
      tags:
      - GuildsService
      summary: GetGuildMembers GuildsService
      description: Get all members a given guild (include default member)
      operationId: GuildsService#GetGuildMembers
      parameters:
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Aliquam sed temporibus error non molestiae est.
        example: Quae numquam blanditiis sit laboriosam necessitatibus eligendi.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGuildMembersResponseBody'
              example:
                members:
                - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
                  is_default_guild_member: false
                  since: 4230233166174377582
                - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
                  is_default_guild_member: false
                  since: 4230233166174377582
                - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
                  is_default_guild_member: false
                  since: 4230233166174377582
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/portfolio:
    get:
      tags:
      - GuildsService
      summary: GetAccountPortfolio GuildsService
      description: Get current account portfolio
      operationId: GuildsService#GetAccountPortfolio
      parameters:
      - name: injective_address
        in: query
        allowEmptyValue: true
        required: true
        schema:
          type: string
          example: Quaerat officiis.
        example: Recusandae non nobis officia veniam sit pariatur.
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Qui ab quam rem blanditiis animi.
        example: Est voluptates.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountPortfolioResponseBody'
              example:
                data:
                  balances:
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  injective_address: Molestias iusto.
                  updated_at: 5451932786486717567
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /guilds/{guildID}/portfolios:
    get:
      tags:
      - GuildsService
      summary: GetAccountPortfolios GuildsService
      description: Get current account portfolios snapshots all the time
      operationId: GuildsService#GetAccountPortfolios
      parameters:
      - name: injective_address
        in: query
        allowEmptyValue: true
        required: true
        schema:
          type: string
          example: Omnis cupiditate ea aperiam distinctio debitis voluptatem.
        example: Unde alias et odio.
      - name: guildID
        in: path
        required: true
        schema:
          type: string
          example: Corrupti quae eius ipsum.
        example: Aut recusandae ratione aliquam amet sunt.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountPortfoliosResponseBody'
              example:
                portfolios:
                - balances:
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  injective_address: Molestias iusto.
                  updated_at: 5451932786486717567
                - balances:
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  injective_address: Molestias iusto.
                  updated_at: 5451932786486717567
                - balances:
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  injective_address: Molestias iusto.
                  updated_at: 5451932786486717567
                - balances:
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  - available_balance: Dolorem nostrum velit non.
                    denom: Eaque qui animi nulla et.
                    margin_hold: Velit ut aliquam.
                    price_usd: 0.6659618906926204
                    total_balance: Autem inventore sed maxime voluptatum.
                    unrealized_pnl: Itaque autem est sit nesciunt ea.
                  injective_address: Molestias iusto.
                  updated_at: 5451932786486717567
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "500":
          description: Internal Server Error response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    Balance:
      type: object
      properties:
        available_balance:
          type: string
          example: Voluptatem ut aut inventore non.
        denom:
          type: string
          example: Eligendi molestiae ab quod dicta animi maxime.
        margin_hold:
          type: string
          example: Vel sit modi voluptate repellat.
        price_usd:
          type: number
          example: 0.59110869532396
          format: double
        total_balance:
          type: string
          example: Vitae doloremque.
        unrealized_pnl:
          type: string
          example: Eveniet libero consectetur saepe recusandae est sequi.
      example:
        available_balance: Consequatur temporibus minima laudantium.
        denom: Maiores nostrum ut cupiditate et.
        margin_hold: Reprehenderit laborum aspernatur.
        price_usd: 0.3891554754042029
        total_balance: Numquam non officiis dolorem nesciunt.
        unrealized_pnl: Et omnis enim tempore natus et.
      required:
      - denom
      - total_balance
      - available_balance
      - unrealized_pnl
      - margin_hold
      - price_usd
    EnterGuildRequestBody:
      type: object
      properties:
        message:
          type: string
          description: 'Supply base64 json encoded string cointaining {"action": "enter-guild",
            "expired_at": unixTimestamp }'
          example: Iusto suscipit recusandae.
        public_key:
          type: string
          example: Est eum aspernatur et.
        signature:
          type: string
          example: Similique facere.
      example:
        message: Perspiciatis enim velit aliquam nisi.
        public_key: Saepe est.
        signature: Incidunt dicta laboriosam.
      required:
      - public_key
      - message
      - signature
    EnterGuildResponseBody:
      type: object
      properties:
        join_status:
          type: string
          example: Qui assumenda ad sunt odit voluptatum illum.
      example:
        join_status: Occaecati nobis et.
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: Not found
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetAccountPortfolioResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/SingleAccountPortfolio'
      example:
        data:
          balances:
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          injective_address: Molestias iusto.
          updated_at: 5451932786486717567
    GetAccountPortfoliosResponseBody:
      type: object
      properties:
        portfolios:
          type: array
          items:
            $ref: '#/components/schemas/SingleAccountPortfolio'
          example:
          - balances:
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            injective_address: Molestias iusto.
            updated_at: 5451932786486717567
          - balances:
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            injective_address: Molestias iusto.
            updated_at: 5451932786486717567
          - balances:
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            - available_balance: Dolorem nostrum velit non.
              denom: Eaque qui animi nulla et.
              margin_hold: Velit ut aliquam.
              price_usd: 0.6659618906926204
              total_balance: Autem inventore sed maxime voluptatum.
              unrealized_pnl: Itaque autem est sit nesciunt ea.
            injective_address: Molestias iusto.
            updated_at: 5451932786486717567
      example:
        portfolios:
        - balances:
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          injective_address: Molestias iusto.
          updated_at: 5451932786486717567
        - balances:
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          injective_address: Molestias iusto.
          updated_at: 5451932786486717567
        - balances:
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          injective_address: Molestias iusto.
          updated_at: 5451932786486717567
    GetAllGuildsResponseBody:
      type: object
      properties:
        guilds:
          type: array
          items:
            $ref: '#/components/schemas/Guild'
          description: Existing guilds
          example:
          - capacity: 2512663142570487689
            derivative_quote_requirement: Ut suscipit iste ex.
            description: Id et quaerat cum.
            id: Aut est sint illum.
            master_address: Ut sunt aut consectetur.
            member_count: 45528291560320936
            name: Voluptatem maiores nulla incidunt quasi quibusdam et.
            spot_base_requirement: Est fuga vel quos rerum.
            spot_quote_requirement: Sit ut.
            staking_requirement: Hic accusantium est nobis dolores.
          - capacity: 2512663142570487689
            derivative_quote_requirement: Ut suscipit iste ex.
            description: Id et quaerat cum.
            id: Aut est sint illum.
            master_address: Ut sunt aut consectetur.
            member_count: 45528291560320936
            name: Voluptatem maiores nulla incidunt quasi quibusdam et.
            spot_base_requirement: Est fuga vel quos rerum.
            spot_quote_requirement: Sit ut.
            staking_requirement: Hic accusantium est nobis dolores.
      example:
        guilds:
        - capacity: 2512663142570487689
          derivative_quote_requirement: Ut suscipit iste ex.
          description: Id et quaerat cum.
          id: Aut est sint illum.
          master_address: Ut sunt aut consectetur.
          member_count: 45528291560320936
          name: Voluptatem maiores nulla incidunt quasi quibusdam et.
          spot_base_requirement: Est fuga vel quos rerum.
          spot_quote_requirement: Sit ut.
          staking_requirement: Hic accusantium est nobis dolores.
        - capacity: 2512663142570487689
          derivative_quote_requirement: Ut suscipit iste ex.
          description: Id et quaerat cum.
          id: Aut est sint illum.
          master_address: Ut sunt aut consectetur.
          member_count: 45528291560320936
          name: Voluptatem maiores nulla incidunt quasi quibusdam et.
          spot_base_requirement: Est fuga vel quos rerum.
          spot_quote_requirement: Sit ut.
          staking_requirement: Hic accusantium est nobis dolores.
    GetGuildDefaultMemberResponseBody:
      type: object
      properties:
        default_member:
          $ref: '#/components/schemas/GuildMember'
      example:
        default_member:
          injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
          is_default_guild_member: false
          since: 4230233166174377582
    GetGuildMarketsResponseBody:
      type: object
      properties:
        markets:
          type: array
          items:
            $ref: '#/components/schemas/Market'
          example:
          - is_perpetual: false
            market_id: Voluptatem ut labore.
          - is_perpetual: false
            market_id: Voluptatem ut labore.
      example:
        markets:
        - is_perpetual: false
          market_id: Voluptatem ut labore.
        - is_perpetual: false
          market_id: Voluptatem ut labore.
    GetGuildMasterAddressResponseBody:
      type: object
      properties:
        master_address:
          type: string
          example: Quia earum.
      example:
        master_address: Dolorem officiis et neque assumenda.
    GetGuildMembersResponseBody:
      type: object
      properties:
        members:
          type: array
          items:
            $ref: '#/components/schemas/GuildMember'
          description: Member of given guild
          example:
          - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
            is_default_guild_member: false
            since: 4230233166174377582
          - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
            is_default_guild_member: false
            since: 4230233166174377582
          - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
            is_default_guild_member: false
            since: 4230233166174377582
      example:
        members:
        - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
          is_default_guild_member: false
          since: 4230233166174377582
        - injective_address: Magni nihil voluptatem voluptatibus nostrum magnam.
          is_default_guild_member: false
          since: 4230233166174377582
    GetSingleGuildResponseBody:
      type: object
      properties:
        guild:
          $ref: '#/components/schemas/Guild'
      example:
        guild:
          capacity: 2512663142570487689
          derivative_quote_requirement: Ut suscipit iste ex.
          description: Id et quaerat cum.
          id: Aut est sint illum.
          master_address: Ut sunt aut consectetur.
          member_count: 45528291560320936
          name: Voluptatem maiores nulla incidunt quasi quibusdam et.
          spot_base_requirement: Est fuga vel quos rerum.
          spot_quote_requirement: Sit ut.
          staking_requirement: Hic accusantium est nobis dolores.
    Guild:
      type: object
      properties:
        capacity:
          type: integer
          example: 4395625031195678811
          format: int64
        derivative_quote_requirement:
          type: string
          example: Omnis beatae dignissimos.
        description:
          type: string
          example: Commodi tempora et dicta omnis.
        id:
          type: string
          example: Iste dolorem.
        master_address:
          type: string
          example: Ratione dolores sit ut nobis.
        member_count:
          type: integer
          example: 4595458242679777265
          format: int64
        name:
          type: string
          example: Corrupti voluptatem ea.
        spot_base_requirement:
          type: string
          example: Cupiditate delectus.
        spot_quote_requirement:
          type: string
          example: Minima quos est.
        staking_requirement:
          type: string
          example: Minima enim ut.
      description: Guild info
      example:
        capacity: 6640115553067528642
        derivative_quote_requirement: Et saepe hic delectus dolores.
        description: Voluptatum quia.
        id: Aut cumque natus optio ut unde.
        master_address: Libero iste quia voluptatibus.
        member_count: 5321978411389238164
        name: Molestias nam et dolor corporis.
        spot_base_requirement: Ipsa nihil dolore corrupti in placeat minima.
        spot_quote_requirement: Tenetur nihil.
        staking_requirement: Est illum dolorum doloribus aut aut.
      required:
      - id
      - name
      - description
      - master_address
      - spot_base_requirement
      - spot_quote_requirement
      - derivative_quote_requirement
      - staking_requirement
      - capacity
      - member_count
    GuildMember:
      type: object
      properties:
        injective_address:
          type: string
          example: Nostrum dolores aut quae.
        is_default_guild_member:
          type: boolean
          example: false
        since:
          type: integer
          example: 4141554117598120519
          format: int64
      description: Guild member metadata
      example:
        injective_address: Qui veniam.
        is_default_guild_member: false
        since: 5910314687459079427
      required:
      - injective_address
      - is_default_guild_member
      - since
    LeaveGuildResponseBody:
      type: object
      properties:
        leave_status:
          type: string
          example: Eligendi molestiae itaque dolor rerum voluptate.
      example:
        leave_status: Pariatur omnis.
    Market:
      type: object
      properties:
        is_perpetual:
          type: boolean
          example: false
        market_id:
          type: string
          example: Voluptate in reprehenderit ea at.
      description: Market supported by guild
      example:
        is_perpetual: true
        market_id: Eaque iusto et qui dolorem in vitae.
      required:
      - market_id
      - is_perpetual
    SingleAccountPortfolio:
      type: object
      properties:
        balances:
          type: array
          items:
            $ref: '#/components/schemas/Balance'
          example:
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
          - available_balance: Dolorem nostrum velit non.
            denom: Eaque qui animi nulla et.
            margin_hold: Velit ut aliquam.
            price_usd: 0.6659618906926204
            total_balance: Autem inventore sed maxime voluptatum.
            unrealized_pnl: Itaque autem est sit nesciunt ea.
        injective_address:
          type: string
          example: In quibusdam ut repellendus consequatur tempore.
        updated_at:
          type: integer
          example: 871276157136164319
          format: int64
      description: Single account portfio snapshot
      example:
        balances:
        - available_balance: Dolorem nostrum velit non.
          denom: Eaque qui animi nulla et.
          margin_hold: Velit ut aliquam.
          price_usd: 0.6659618906926204
          total_balance: Autem inventore sed maxime voluptatum.
          unrealized_pnl: Itaque autem est sit nesciunt ea.
        - available_balance: Dolorem nostrum velit non.
          denom: Eaque qui animi nulla et.
          margin_hold: Velit ut aliquam.
          price_usd: 0.6659618906926204
          total_balance: Autem inventore sed maxime voluptatum.
          unrealized_pnl: Itaque autem est sit nesciunt ea.
        - available_balance: Dolorem nostrum velit non.
          denom: Eaque qui animi nulla et.
          margin_hold: Velit ut aliquam.
          price_usd: 0.6659618906926204
          total_balance: Autem inventore sed maxime voluptatum.
          unrealized_pnl: Itaque autem est sit nesciunt ea.
        injective_address: Aut saepe molestiae incidunt sed quo.
        updated_at: 8601143133824164228
      required:
      - injective_address
      - balances
      - updated_at
tags:
- name: GuildsService
  description: Service supports trading guild queries
