swagger: "2.0"
info:
  title: Injective Guilds Service
  description: HTTP server for the Trading guilds query
  version: ""
host: 0.0.0.0:9930
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /guilds:
    get:
      tags:
      - GuildService
      summary: GetAllGuilds GuildService
      description: Get all guilds
      operationId: GuildService#GetAllGuilds
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetAllGuildsNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetAllGuildsInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetAllGuildsResponseBody'
      schemes:
      - http
  /guilds/{guildID}:
    get:
      tags:
      - GuildService
      summary: GetSingleGuild GuildService
      description: Get a single guild
      operationId: GuildService#GetSingleGuild
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetSingleGuildNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetSingleGuildInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetSingleGuildResponseBody'
      schemes:
      - http
  /guilds/{guildID}/default-guild-member:
    get:
      tags:
      - GuildService
      summary: GetGuildDefaultMember GuildService
      operationId: GuildService#GetGuildDefaultMember
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildDefaultMemberNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildDefaultMemberInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetGuildDefaultMemberResponseBody'
      schemes:
      - http
  /guilds/{guildID}/guild-master:
    get:
      tags:
      - GuildService
      summary: GetGuildMasterAddress GuildService
      description: Get master address of given guild
      operationId: GuildService#GetGuildMasterAddress
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMasterAddressNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMasterAddressInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMasterAddressResponseBody'
      schemes:
      - http
  /guilds/{guildID}/markets:
    get:
      tags:
      - GuildService
      summary: GetGuildMarkets GuildService
      operationId: GuildService#GetGuildMarkets
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMarketsNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMarketsInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMarketsResponseBody'
      schemes:
      - http
  /guilds/{guildID}/member:
    post:
      tags:
      - GuildService
      summary: EnterGuild GuildService
      operationId: GuildService#EnterGuild
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      - name: EnterGuildRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/GuildServiceEnterGuildRequestBody'
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceEnterGuildNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceEnterGuildInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceEnterGuildResponseBody'
      schemes:
      - http
    delete:
      tags:
      - GuildService
      summary: LeaveGuild GuildService
      operationId: GuildService#LeaveGuild
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      - name: LeaveGuildRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/GuildServiceLeaveGuildRequestBody'
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceLeaveGuildNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceLeaveGuildInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceLeaveGuildResponseBody'
      schemes:
      - http
  /guilds/{guildID}/members:
    get:
      tags:
      - GuildService
      summary: GetGuildMembers GuildService
      description: Get members
      operationId: GuildService#GetGuildMembers
      parameters:
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMembersNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMembersInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetGuildMembersResponseBody'
      schemes:
      - http
  /guilds/{guildID}/portfolio:
    get:
      tags:
      - GuildService
      summary: GetAccountPortfolios GuildService
      operationId: GuildService#GetAccountPortfolios
      parameters:
      - name: injective_address
        in: query
        required: true
        type: string
      - name: guildID
        in: path
        required: true
        type: string
      responses:
        "5":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetAccountPortfoliosNotFoundResponseBody'
        "13":
          description: ' response.'
          schema:
            $ref: '#/definitions/GuildServiceGetAccountPortfoliosInternalResponseBody'
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/GuildServiceGetAccountPortfoliosResponseBody'
      schemes:
      - http
definitions:
  AccountPorfoliosResponseBody:
    title: AccountPorfoliosResponseBody
    type: object
    properties:
      injective_address:
        type: string
        example: Non sit et.
      portfolios:
        type: array
        items:
          $ref: '#/definitions/EmbededAccountPortfolioResponseBody'
        example:
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
    description: Account portfio snapshots
    example:
      injective_address: In eos quae nemo fugiat autem aliquid.
      portfolios:
      - available_balance: Accusamus aliquid quo delectus cupiditate optio.
        denom: Ea et mollitia.
        margin_hold: Odio porro tempore consectetur et corrupti.
        total_balance: Repellendus ex sit consequatur.
        unrealized_pnl: Voluptas culpa.
        updated_at: "1977-02-05T21:09:14Z"
      - available_balance: Accusamus aliquid quo delectus cupiditate optio.
        denom: Ea et mollitia.
        margin_hold: Odio porro tempore consectetur et corrupti.
        total_balance: Repellendus ex sit consequatur.
        unrealized_pnl: Voluptas culpa.
        updated_at: "1977-02-05T21:09:14Z"
      - available_balance: Accusamus aliquid quo delectus cupiditate optio.
        denom: Ea et mollitia.
        margin_hold: Odio porro tempore consectetur et corrupti.
        total_balance: Repellendus ex sit consequatur.
        unrealized_pnl: Voluptas culpa.
        updated_at: "1977-02-05T21:09:14Z"
      - available_balance: Accusamus aliquid quo delectus cupiditate optio.
        denom: Ea et mollitia.
        margin_hold: Odio porro tempore consectetur et corrupti.
        total_balance: Repellendus ex sit consequatur.
        unrealized_pnl: Voluptas culpa.
        updated_at: "1977-02-05T21:09:14Z"
    required:
    - injective_address
    - portfolios
  EmbededAccountPortfolioResponseBody:
    title: EmbededAccountPortfolioResponseBody
    type: object
    properties:
      available_balance:
        type: string
        example: Tenetur laboriosam culpa et accusantium.
      denom:
        type: string
        example: Repudiandae rem deserunt.
      margin_hold:
        type: string
        example: Quo tenetur numquam.
      total_balance:
        type: string
        example: Possimus aspernatur beatae reiciendis nostrum.
      unrealized_pnl:
        type: string
        example: In velit atque beatae eum.
      updated_at:
        type: string
        example: "1981-08-30T04:53:10Z"
        format: date-time
    example:
      available_balance: Ipsum doloremque.
      denom: Distinctio debitis voluptatem aut unde alias et.
      margin_hold: Sed officia consequuntur quis et inventore numquam.
      total_balance: Quis corrupti quae.
      unrealized_pnl: Recusandae ratione aliquam amet sunt ut earum.
      updated_at: "1992-03-06T05:10:15Z"
    required:
    - denom
    - total_balance
    - available_balance
    - unrealized_pnl
    - margin_hold
    - updated_at
  GuildMemberResponseBody:
    title: GuildMemberResponseBody
    type: object
    properties:
      injective_address:
        type: string
        example: Ducimus perspiciatis cupiditate ex.
      is_default_guild_member:
        type: boolean
        example: false
    description: Guild member metadata
    example:
      injective_address: Qui laudantium commodi officia autem.
      is_default_guild_member: false
  GuildResponseBody:
    title: GuildResponseBody
    type: object
    properties:
      capacity:
        type: integer
        example: 4607263661426551867
        format: int64
      derivative_quote_requirement:
        type: string
        example: Quos iste magni.
      description:
        type: string
        example: Repudiandae officiis.
      id:
        type: string
        example: Qui veniam.
      master_address:
        type: string
        example: Cum eius occaecati excepturi odit et.
      name:
        type: string
        example: Vitae veniam dicta temporibus et.
      spot_base_requirement:
        type: string
        example: Quasi aut omnis voluptates.
      spot_quote_requirement:
        type: string
        example: Enim nam rerum perferendis pariatur velit.
      staking_requirement:
        type: string
        example: Rerum sit.
    description: Guild info
    example:
      capacity: 2433966877279338552
      derivative_quote_requirement: Hic eveniet dolor repellendus non.
      description: Rerum est rerum.
      id: Quia est voluptatem dolor eligendi quam.
      master_address: Quis tenetur.
      name: Qui quae.
      spot_base_requirement: Eius sit perferendis nam quasi expedita numquam.
      spot_quote_requirement: Et quo.
      staking_requirement: Sed illum a fugiat saepe recusandae.
    required:
    - id
    - name
    - description
    - spot_base_requirement
    - spot_quote_requirement
    - staking_requirement
    - capacity
  GuildServiceEnterGuildInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceEnterGuildNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceEnterGuildRequestBody:
    title: GuildServiceEnterGuildRequestBody
    type: object
    properties:
      message:
        type: string
        example: Tempora et dicta omnis minima.
      public_key:
        type: string
        example: Voluptatem ea dolores.
      signature:
        type: string
        example: Dolores sit ut nobis est.
    example:
      message: Est porro omnis beatae.
      public_key: Delectus asperiores minima.
      signature: Quia minima enim ut.
  GuildServiceEnterGuildResponseBody:
    title: GuildServiceEnterGuildResponseBody
    type: object
    properties:
      join_status:
        type: string
        example: Alias et illum est aut.
    example:
      join_status: Nihil vel qui iste qui magnam.
  GuildServiceGetAccountPortfolioInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAccountPortfolioNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAccountPortfolioResponseBody:
    title: GuildServiceGetAccountPortfolioResponseBody
    type: object
    properties:
      data:
        $ref: '#/definitions/SingleAccountPortfolioResponseBody'
    example:
      data:
        available_balance: Ratione minus qui.
        denom: Qui et est iste qui consequatur.
        injective_address: In odio est dolorem sint eos.
        margin_hold: Esse cupiditate exercitationem distinctio.
        total_balance: Quos id itaque velit.
        unrealized_pnl: Nihil dignissimos consequatur cupiditate adipisci iste.
        updated_at: "1992-11-07T22:49:37Z"
  GuildServiceGetAccountPortfoliosInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAccountPortfoliosNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAccountPortfoliosResponseBody:
    title: GuildServiceGetAccountPortfoliosResponseBody
    type: object
    properties:
      data:
        $ref: '#/definitions/AccountPorfoliosResponseBody'
    example:
      data:
        injective_address: In iste.
        portfolios:
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
        - available_balance: Accusamus aliquid quo delectus cupiditate optio.
          denom: Ea et mollitia.
          margin_hold: Odio porro tempore consectetur et corrupti.
          total_balance: Repellendus ex sit consequatur.
          unrealized_pnl: Voluptas culpa.
          updated_at: "1977-02-05T21:09:14Z"
  GuildServiceGetAllGuildsInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAllGuildsNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Not found (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetAllGuildsResponseBody:
    title: GuildServiceGetAllGuildsResponseBody
    type: object
    properties:
      guilds:
        type: array
        items:
          $ref: '#/definitions/GuildResponseBody'
        description: Existing guilds
        example:
        - capacity: 6362405101647038215
          derivative_quote_requirement: Harum eum vel quia.
          description: Nihil quia quo eligendi omnis.
          id: Adipisci reiciendis minima id.
          master_address: Adipisci sed libero a nam consectetur.
          name: Dolore atque aperiam officiis necessitatibus dicta est.
          spot_base_requirement: Dolor commodi soluta dolores aut.
          spot_quote_requirement: Voluptates est.
          staking_requirement: Et placeat id.
        - capacity: 6362405101647038215
          derivative_quote_requirement: Harum eum vel quia.
          description: Nihil quia quo eligendi omnis.
          id: Adipisci reiciendis minima id.
          master_address: Adipisci sed libero a nam consectetur.
          name: Dolore atque aperiam officiis necessitatibus dicta est.
          spot_base_requirement: Dolor commodi soluta dolores aut.
          spot_quote_requirement: Voluptates est.
          staking_requirement: Et placeat id.
    example:
      guilds:
      - capacity: 6362405101647038215
        derivative_quote_requirement: Harum eum vel quia.
        description: Nihil quia quo eligendi omnis.
        id: Adipisci reiciendis minima id.
        master_address: Adipisci sed libero a nam consectetur.
        name: Dolore atque aperiam officiis necessitatibus dicta est.
        spot_base_requirement: Dolor commodi soluta dolores aut.
        spot_quote_requirement: Voluptates est.
        staking_requirement: Et placeat id.
      - capacity: 6362405101647038215
        derivative_quote_requirement: Harum eum vel quia.
        description: Nihil quia quo eligendi omnis.
        id: Adipisci reiciendis minima id.
        master_address: Adipisci sed libero a nam consectetur.
        name: Dolore atque aperiam officiis necessitatibus dicta est.
        spot_base_requirement: Dolor commodi soluta dolores aut.
        spot_quote_requirement: Voluptates est.
        staking_requirement: Et placeat id.
      - capacity: 6362405101647038215
        derivative_quote_requirement: Harum eum vel quia.
        description: Nihil quia quo eligendi omnis.
        id: Adipisci reiciendis minima id.
        master_address: Adipisci sed libero a nam consectetur.
        name: Dolore atque aperiam officiis necessitatibus dicta est.
        spot_base_requirement: Dolor commodi soluta dolores aut.
        spot_quote_requirement: Voluptates est.
        staking_requirement: Et placeat id.
      - capacity: 6362405101647038215
        derivative_quote_requirement: Harum eum vel quia.
        description: Nihil quia quo eligendi omnis.
        id: Adipisci reiciendis minima id.
        master_address: Adipisci sed libero a nam consectetur.
        name: Dolore atque aperiam officiis necessitatibus dicta est.
        spot_base_requirement: Dolor commodi soluta dolores aut.
        spot_quote_requirement: Voluptates est.
        staking_requirement: Et placeat id.
  GuildServiceGetGuildDefaultMemberInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildDefaultMemberNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Not found (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildDefaultMemberResponseBody:
    title: GuildServiceGetGuildDefaultMemberResponseBody
    type: object
    properties:
      default_member:
        $ref: '#/definitions/GuildMemberResponseBody'
    example:
      default_member:
        injective_address: Provident odio deserunt.
        is_default_guild_member: false
  GuildServiceGetGuildMarketsInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMarketsNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMarketsResponseBody:
    title: GuildServiceGetGuildMarketsResponseBody
    type: object
    properties:
      markets:
        type: array
        items:
          $ref: '#/definitions/MarketResponseBody'
        example:
        - is_perpetual: true
          market_id: Necessitatibus at magni doloribus consequuntur.
        - is_perpetual: true
          market_id: Necessitatibus at magni doloribus consequuntur.
        - is_perpetual: true
          market_id: Necessitatibus at magni doloribus consequuntur.
        - is_perpetual: true
          market_id: Necessitatibus at magni doloribus consequuntur.
    example:
      markets:
      - is_perpetual: true
        market_id: Necessitatibus at magni doloribus consequuntur.
      - is_perpetual: true
        market_id: Necessitatibus at magni doloribus consequuntur.
      - is_perpetual: true
        market_id: Necessitatibus at magni doloribus consequuntur.
      - is_perpetual: true
        market_id: Necessitatibus at magni doloribus consequuntur.
  GuildServiceGetGuildMasterAddressInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMasterAddressNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMasterAddressResponseBody:
    title: GuildServiceGetGuildMasterAddressResponseBody
    type: object
    properties:
      master_address:
        type: string
        example: Accusamus vel sit libero vitae neque eveniet.
    example:
      master_address: Et rerum facilis quibusdam repellat.
  GuildServiceGetGuildMembersInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMembersNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Not found (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetGuildMembersResponseBody:
    title: GuildServiceGetGuildMembersResponseBody
    type: object
    properties:
      members:
        type: array
        items:
          $ref: '#/definitions/GuildMemberResponseBody'
        description: Member of given guild
        example:
        - injective_address: Provident odio deserunt.
          is_default_guild_member: false
        - injective_address: Provident odio deserunt.
          is_default_guild_member: false
        - injective_address: Provident odio deserunt.
          is_default_guild_member: false
    example:
      members:
      - injective_address: Provident odio deserunt.
        is_default_guild_member: false
      - injective_address: Provident odio deserunt.
        is_default_guild_member: false
      - injective_address: Provident odio deserunt.
        is_default_guild_member: false
  GuildServiceGetSingleGuildInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetSingleGuildNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceGetSingleGuildResponseBody:
    title: GuildServiceGetSingleGuildResponseBody
    type: object
    properties:
      guild:
        $ref: '#/definitions/GuildResponseBody'
    example:
      guild:
        capacity: 6362405101647038215
        derivative_quote_requirement: Harum eum vel quia.
        description: Nihil quia quo eligendi omnis.
        id: Adipisci reiciendis minima id.
        master_address: Adipisci sed libero a nam consectetur.
        name: Dolore atque aperiam officiis necessitatibus dicta est.
        spot_base_requirement: Dolor commodi soluta dolores aut.
        spot_quote_requirement: Voluptates est.
        staking_requirement: Et placeat id.
  GuildServiceLeaveGuildInternalResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Internal Server Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceLeaveGuildNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Not found (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  GuildServiceLeaveGuildRequestBody:
    title: GuildServiceLeaveGuildRequestBody
    type: object
    properties:
      message:
        type: string
        example: Placeat minima ducimus tenetur nihil architecto et.
      public_key:
        type: string
        example: Nihil dolore corrupti.
      signature:
        type: string
        example: Hic delectus dolores officiis est.
    example:
      message: Quia est reprehenderit eos.
      public_key: Dolorum doloribus aut aut.
      signature: Rem blanditiis nostrum dolores aut quae recusandae.
  GuildServiceLeaveGuildResponseBody:
    title: GuildServiceLeaveGuildResponseBody
    type: object
    properties:
      leave_status:
        type: string
        example: Ipsum beatae aut cumque natus optio ut.
    example:
      leave_status: Sit molestias nam.
  MarketResponseBody:
    title: MarketResponseBody
    type: object
    properties:
      is_perpetual:
        type: boolean
        example: false
      market_id:
        type: string
        example: Et qui veniam asperiores omnis aut.
    description: Market supported by guild
    example:
      is_perpetual: true
      market_id: Quia earum.
    required:
    - market_id
    - is_perpetual
  SingleAccountPortfolioResponseBody:
    title: SingleAccountPortfolioResponseBody
    type: object
    properties:
      available_balance:
        type: string
        example: Incidunt dicta laboriosam.
      denom:
        type: string
        example: Saepe est.
      injective_address:
        type: string
        example: Similique facere.
      margin_hold:
        type: string
        example: Occaecati nobis et.
      total_balance:
        type: string
        example: Perspiciatis enim velit aliquam nisi.
      unrealized_pnl:
        type: string
        example: Qui assumenda ad sunt odit voluptatum illum.
      updated_at:
        type: string
        example: "1974-02-25T22:03:53Z"
        format: date-time
    description: Account portfio snapshot
    example:
      available_balance: Vel sit modi voluptate repellat.
      denom: Inventore non.
      injective_address: Corporis voluptatem ut.
      margin_hold: Non officiis dolorem nesciunt.
      total_balance: Eveniet libero consectetur saepe recusandae est sequi.
      unrealized_pnl: Et maiores nostrum ut cupiditate et placeat.
      updated_at: "1992-08-10T09:19:56Z"
    required:
    - injective_address
    - denom
    - total_balance
    - available_balance
    - unrealized_pnl
    - margin_hold
    - updated_at
